### ISSUE TITLE
[Experimental-Branch] Slave-node not working properly. Segmentation fault of unknown cause.

### ISSUE THREAD

**Issue by FranciscoThiesen** [sdec-brasil/docker-multichain#2]
When running the containers I have obtained a segmentation fault.
![2019-04-07-195957_2460x962_scrot](https://user-images.githubusercontent.com/8302742/55691108-d0744200-5970-11e9-9b93-2817709de2c2.png)

**Comment by tloriato** [comment]
Tava no branch experimental mesmo? No branch mysqlviewv2 eu tinha mexido em um negóciozinho do slavenode, será que ele não usou uma build/imagem antiga? :persevere:

Aconteceu muitas vezes?

**Comment by FranciscoThiesen** [comment]
Mudei o Dockerfile e setupexplorer.sh para os que você me mandou mais cedo via pastebin e esse comportamento parou. O interessante é que não toquei em nenhum arquivo do cointainer do slavenode.

Sim, tava no experimental mesmo.

**Comment by tloriato** [comment]
Muito estranho isso 🤔
